---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/metalmatze/transmission-exporter

steps:
- name: build
  pull: default
  image: golang:1.13-alpine
  environment:
    GOPROXY: https://proxy.golang.org
  commands:
  - apk add -U git make
  - make fmt
  - make vet
  - make lint
  - make build

- name: docker-master
  pull: always
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jereksel/transmission-exporter
    tags:
    - master
  when:
    branch:
    - master
    event:
    - push

...
